/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tdder.junit.jupiter.teardown;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
